import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import type { AppRoute } from '@/navigation';
import type { FreePool, LessonEntry, SearchItem } from '@/types';
import { api } from '@/services/api';
import { content, songCoverFromPath, storyCoverFromPath } from '@/services/content';
import { usePlayer } from '@/state/PlayerContext';
import { useSession } from '@/state/SessionContext';
import { Card, colors, Cover, Empty, Loading, PrimaryButton, SectionHeader, StatusPill } from '@/components/Ui';
import { Icon } from '@/components/Icon';

export function CommonScreen({ route, onBack }: { route: AppRoute; onBack: () => void }) {
  if (route.name === 'free-zone') return <FreeZone initialTab={route.tab ?? 'story'} onBack={onBack} />;
  if (route.name === 'search') return <SearchScreen scope={route.scope} onBack={onBack} />;
  if (route.name === 'favorites') return <FavoritesScreen initialTab={route.tab ?? 'story'} onBack={onBack} />;
  if (route.name === 'history') return <HistoryScreen onBack={onBack} />;
  if (route.name === 'children') return <ChildrenScreen onBack={onBack} />;
  if (route.name === 'settings') return <SettingsScreen onBack={onBack} />;
  if (route.name === 'lessons') return <LessonsScreen subject={route.subject} onBack={onBack} />;
  if (route.name === 'collection') return <CollectionScreen onBack={onBack} />;
  if (route.name === 'challenge') return <ChallengeScreen subject={route.subject} initialLesson={route.lesson} onBack={onBack} />;
  return <MembershipScreen onBack={onBack} />;
}

function Header({ title, onBack, right }: { title: string; onBack: () => void; right?: React.ReactNode }) {
  const dark = title === '鎏金故事书匣';
  return <View style={styles.header}><Pressable accessibilityLabel="返回" onPress={onBack} style={styles.headerButton}><Icon name="back" size={28} color={dark ? '#fff' : colors.ink} /></Pressable><Text style={[styles.headerTitle, dark && { color: '#fff' }]}>{title}</Text><View style={styles.headerButton}>{right}</View></View>;
}

function Segments({ tab, setTab, labels = ['故事', '歌曲'] }: { tab: 'story' | 'song'; setTab: (tab: 'story' | 'song') => void; labels?: [string, string] }) {
  return <View style={styles.segment}><Pressable onPress={() => setTab('story')} style={[styles.segmentButton, tab === 'story' && styles.segmentActive]}><Icon name="book" size={20} color={tab === 'story' ? '#fff' : colors.orange} /><Text style={[styles.segmentText, tab === 'story' && styles.segmentTextActive]}>{labels[0]}</Text></Pressable><Pressable onPress={() => setTab('song')} style={[styles.segmentButton, tab === 'song' && styles.segmentActive]}><Icon name="music" size={20} color={tab === 'song' ? '#fff' : colors.orange} /><Text style={[styles.segmentText, tab === 'song' && styles.segmentTextActive]}>{labels[1]}</Text></Pressable></View>;
}

function FreeZone({ initialTab, onBack }: { initialTab: 'story' | 'song'; onBack: () => void }) {
  const player = usePlayer();
  const [tab, setTab] = useState(initialTab);
  const [pool, setPool] = useState<FreePool | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void content.freePool().then(setPool).finally(() => setLoading(false)); }, []);
  const items = tab === 'story' ? pool?.stories ?? [] : pool?.songs ?? [];
  const play = async (index: number) => {
    if (!pool) return;
    if (tab === 'song') { const tracks = pool.songs.map((item) => content.song({ path: item.p, title: item.t })); player.playQueue(tracks, index); return; }
    setLoading(true);
    try { const window = pool.stories.slice(Math.max(0, index - 2), index + 5); const tracks = await Promise.all(window.map((item) => content.story(item.p, item.t, storyCoverFromPath(item.p)))); player.playQueue(tracks, Math.min(2, index)); }
    finally { setLoading(false); }
  };
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title="免费专区" onBack={onBack} /><Text style={styles.pageSubtitle}>精选免费内容，未登录或权益到期后仍可畅听</Text><Segments tab={tab} setTab={setTab} labels={[`故事 ${pool?.stories.length ?? 0}`, `歌曲 ${pool?.songs.length ?? 0}`]} />{loading && !pool ? <Loading /> : null}<SectionHeader title={tab === 'story' ? '免费故事' : '免费儿歌'} action={`${items.length} 个`} />{items.map((item, index) => <ContentRow key={item.p} title={tab === 'song' ? item.t.replace(/^(中文|英文|双语)\s*[-－]\s*/, '') : item.t} note={`${item.s} · 免费畅听`} image={tab === 'story' ? storyCoverFromPath(item.p) : songCoverFromPath(item.p)} onPress={() => void play(index)} />)}</ScrollView>;
}

function SearchScreen({ scope, onBack }: { scope: 'story' | 'song' | 'growth'; onBack: () => void }) {
  const session = useSession(); const player = usePlayer();
  const [query, setQuery] = useState(''); const [items, setItems] = useState<SearchItem[]>([]); const [lessons, setLessons] = useState<Array<LessonEntry & { subject: '识字' | '英语' }>>([]); const [loading, setLoading] = useState(false);
  useEffect(() => { setLoading(true); if (scope === 'growth') { void Promise.all([content.lessons('识字'), content.lessons('英语')]).then(([w, e]) => setLessons([...w.map((x) => ({ ...x, subject: '识字' as const })), ...e.map((x) => ({ ...x, subject: '英语' as const }))])).finally(() => setLoading(false)); } else { void content.search(scope).then((result) => setItems(result.list)).finally(() => setLoading(false)); } }, [scope]);
  const hits = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return []; return scope === 'growth' ? lessons.filter((item) => item.text.toLowerCase().includes(q) || item.id.toLowerCase().includes(q)).slice(0, 30) : items.filter((item) => item.t.toLowerCase().includes(q) || item.s.toLowerCase().includes(q)).slice(0, 30); }, [items, lessons, query, scope]);
  const open = async (item: SearchItem | (LessonEntry & { subject: '识字' | '英语' })) => {
    if ('text' in item) { if (item.seq >= 10 && !session.profile?.can_access_all) { Alert.alert('需要权益', '识字/英语前 10 课免费。'); return; } player.play(content.lesson(item, item.subject)); return; }
    if (item.c) { Alert.alert('章回作品', '请从故事首页进入作品目录选择章节。'); return; }
    if (!session.profile?.can_access_all && !await content.isFree(scope as 'story' | 'song', item.p)) { Alert.alert('这是权益内容', '可以先到免费专区继续收听。'); return; }
    if (scope === 'story') player.play(await content.story(item.p, item.t, storyCoverFromPath(item.p))); else player.play(content.song({ path: item.p, title: item.t }));
  };
  const hot = scope === 'story' ? ['三国', '哪吒', '成语', '西游', '恐龙'] : scope === 'song' ? ['摇篮曲', '刘备', '恐龙', '诗词'] : ['的', 'apple', '识字', '英语'];
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent} keyboardShouldPersistTaps="handled"><Header title={`${scope === 'story' ? '故事' : scope === 'song' ? '歌曲' : '成长'}搜索`} onBack={onBack} /><View style={styles.searchBox}><Icon name="search" size={22} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder={scope === 'growth' ? '搜字 / 单词…' : scope === 'story' ? '搜故事名 / 学科…' : '搜歌名 / 歌单…'} style={styles.searchInput} /></View>{!query ? <><SectionHeader title="🔥 热门搜索" /><View style={styles.chips}>{hot.map((word) => <Pressable key={word} onPress={() => setQuery(word)} style={styles.chip}><Text style={styles.chipText}>{word}</Text></Pressable>)}</View><SectionHeader title="💡 小贴士" /><Card><Text style={styles.tip}>搜索范围已按当前 Tab 隔离，不会把故事、歌曲和成长结果混在一起。</Text><Text style={styles.tip}>可搜索具体故事/歌名，也可搜索学科、歌单、单字或英文单词。</Text></Card></> : null}{loading ? <Loading label="索引加载中…" /> : null}{query && !loading && !hits.length ? <Empty text={`没有找到“${query}”`} /> : null}{hits.map((item) => { const lesson = 'text' in item; const title = lesson ? item.text : item.t; const note = lesson ? `${item.subject} · 第 ${item.seq + 1} 课` : item.s; const path = lesson ? item.path : item.p; return <ContentRow key={`${path}-${title}`} title={title} note={note} image={lesson ? undefined : scope === 'story' ? storyCoverFromPath(path) : songCoverFromPath(path)} onPress={() => void open(item)} />; })}</ScrollView>;
}

interface Favorite { favorite_id: string; content_type: 'story' | 'song' | 'lesson'; content_id: string; title: string | null }
function FavoritesScreen({ initialTab, onBack }: { initialTab: 'story' | 'song'; onBack: () => void }) {
  const player = usePlayer(); const session = useSession(); const [tab, setTab] = useState(initialTab); const [list, setList] = useState<Favorite[]>([]); const [loading, setLoading] = useState(true);
  const load = () => { if (!session.loggedIn) { setLoading(false); return; } setLoading(true); void api<{ list: Favorite[] }>('/favorites').then((result) => setList(result.list)).catch(() => setList([])).finally(() => setLoading(false)); };
  useEffect(load, [session.loggedIn]);
  const shown = list.filter((item) => item.content_type === tab);
  const play = async (item: Favorite) => { if (!session.profile?.can_access_all && !await content.isFree(tab, item.content_id)) { Alert.alert('当前无权益', '这个收藏已不在免费范围，可以先听免费专区。'); return; } if (tab === 'story') player.play(await content.story(item.content_id, item.title ?? '收藏故事', storyCoverFromPath(item.content_id))); else player.play(content.song({ path: item.content_id, title: item.title ?? '收藏歌曲' })); };
  const remove = async (id: string) => { await api(`/favorites/${id}`, { method: 'DELETE' }); setList((current) => current.filter((item) => item.favorite_id !== id)); };
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title="我的收藏" onBack={onBack} /><Segments tab={tab} setTab={setTab} />{loading ? <Loading /> : null}{!loading && !shown.length ? <Empty text={session.loggedIn ? '还没有收藏内容' : '登录后查看 App 独立收藏'} /> : null}{shown.map((item) => <View key={item.favorite_id} style={styles.manageRow}><Pressable onPress={() => void play(item)} style={styles.manageMain}><Cover uri={tab === 'story' ? storyCoverFromPath(item.content_id) : songCoverFromPath(item.content_id)} /><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{item.title ?? item.content_id}</Text><Text style={styles.rowNote}>点按播放</Text></View></Pressable><Pressable onPress={() => void remove(item.favorite_id)} style={styles.removeButton}><Text style={styles.removeText}>取消</Text></Pressable></View>)}</ScrollView>;
}

interface History { history_id: string; content_type: 'story' | 'song'; content_id: string; title: string | null; played_at: string }
function HistoryScreen({ onBack }: { onBack: () => void }) {
  const player = usePlayer(); const session = useSession(); const [tab, setTab] = useState<'story' | 'song'>('story'); const [list, setList] = useState<History[]>([]); const [loading, setLoading] = useState(true);
  const load = () => { if (!session.childId) { setLoading(false); return; } setLoading(true); void api<{ list: History[] }>(`/history?child_id=${encodeURIComponent(session.childId)}`).then((result) => setList(result.list)).catch(() => setList([])).finally(() => setLoading(false)); };
  useEffect(load, [session.childId]); const shown = list.filter((item) => item.content_type === tab);
  const play = async (item: History) => { if (!session.profile?.can_access_all && !await content.isFree(tab, item.content_id)) { Alert.alert('当前无权益', '请先听免费专区内容。'); return; } if (tab === 'story') player.play(await content.story(item.content_id, item.title ?? '历史故事', storyCoverFromPath(item.content_id))); else player.play(content.song({ path: item.content_id, title: item.title ?? '历史歌曲' })); };
  const clear = () => Alert.alert('清空播放历史？', '将清空当前孩子的全部播放记录。', [{ text: '取消', style: 'cancel' }, { text: '清空', style: 'destructive', onPress: () => session.childId ? void api(`/history?child_id=${encodeURIComponent(session.childId)}`, { method: 'DELETE' }).then(() => setList([])) : undefined }]);
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title="播放历史" onBack={onBack} right={<Pressable onPress={clear}><Text style={styles.headerAction}>清空</Text></Pressable>} /><Segments tab={tab} setTab={setTab} />{loading ? <Loading /> : null}{!loading && !shown.length ? <Empty text="暂无播放记录" /> : null}{shown.map((item) => <ContentRow key={item.history_id} title={item.title ?? item.content_id} note={new Date(item.played_at).toLocaleString()} image={tab === 'story' ? storyCoverFromPath(item.content_id) : songCoverFromPath(item.content_id)} onPress={() => void play(item)} />)}</ScrollView>;
}

interface Child { child_id: string; child_name: string }
function ChildrenScreen({ onBack }: { onBack: () => void }) {
  const [list, setList] = useState<Child[]>([]); const [name, setName] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); void api<Child[]>('/children').then(setList).catch(() => setList([])).finally(() => setLoading(false)); }; useEffect(load, []);
  const add = async () => { const clean = name.trim(); if (!clean) return; const child = await api<Child>('/children', { method: 'POST', body: JSON.stringify({ child_name: clean }) }); setList((current) => [...current, child]); setName(''); };
  const remove = (child: Child) => Alert.alert(`删除“${child.child_name}”？`, '成长、历史与挑战记录将一并删除；至少保留一个档案。', [
    { text: '取消', style: 'cancel' },
    { text: '删除', style: 'destructive', onPress: () => void api(`/children/${child.child_id}`, { method: 'DELETE' }).then(() => setList((current) => current.filter((item) => item.child_id !== child.child_id))).catch((e) => Alert.alert('删除失败', e instanceof Error ? e.message : '请稍后重试')) },
  ]);
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent} keyboardShouldPersistTaps="handled"><Header title="孩子档案" onBack={onBack} /><View style={styles.addRow}><TextInput value={name} onChangeText={setName} maxLength={32} placeholder="孩子昵称" style={styles.nameInput} /><Pressable onPress={() => void add()} style={styles.addButton}><Text style={styles.addText}>新增</Text></Pressable></View>{loading ? <Loading /> : null}{list.map((child) => <View key={child.child_id} style={styles.childRow}><View style={styles.childAvatar}><Icon name="family" size={27} color={colors.purple} /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{child.child_name}</Text><Text style={styles.rowNote}>独立成长档案</Text></View><Pressable onPress={() => remove(child)}><Text style={styles.removeText}>删除</Text></Pressable></View>)}</ScrollView>;
}

function LessonsScreen({ subject, onBack }: { subject: '识字' | '英语'; onBack: () => void }) {
  const player = usePlayer(); const session = useSession(); const [list, setList] = useState<LessonEntry[]>([]); const [page, setPage] = useState(1); const [onlyFree, setOnlyFree] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { void content.lessons(subject).then(setList).finally(() => setLoading(false)); }, [subject]);
  const filtered = onlyFree ? list.filter((item) => item.seq < 10) : list; const shown = filtered.slice(0, page * 30);
  const play = (item: LessonEntry) => { if (item.seq >= 10 && !session.profile?.can_access_all) { Alert.alert('这里需要爸爸妈妈帮忙打开', '前 10 课免费；第 11 课起需要活动体验或会员权益。'); return; } player.play(content.lesson(item, subject)); if (session.childId) void api('/progress/study', { method: 'POST', body: JSON.stringify({ child_id: session.childId, subject, word_id: item.id, word_text: item.text, study_type: 'study1' }) }).catch(() => undefined); };
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title={`${subject} · 交朋友`} onBack={onBack} /><View style={styles.filterRow}><Pressable onPress={() => setOnlyFree(false)} style={[styles.filter, !onlyFree && styles.filterActive]}><Text style={[styles.filterText, !onlyFree && styles.filterTextActive]}>全部课程</Text></Pressable><Pressable onPress={() => setOnlyFree(true)} style={[styles.filter, onlyFree && styles.filterActive]}><Text style={[styles.filterText, onlyFree && styles.filterTextActive]}>前 10 课免费</Text></Pressable></View>{loading ? <Loading /> : null}{shown.map((item) => { const locked = item.seq >= 10 && !session.profile?.can_access_all; return <View key={item.id} style={styles.lessonRow}><Pressable onPress={() => play(item)} style={styles.lessonMain}><View style={[styles.lessonWord, subject === '英语' && styles.lessonEnglish]}><Text numberOfLines={1} style={[styles.lessonWordText, subject === '英语' && styles.lessonEnglishText]}>{item.text}</Text></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>第 {item.seq + 1} 课</Text><Text style={styles.rowNote}>{locked ? '🔒 需权益' : '认一认 · 点按播放'}</Text></View><Icon name="play" size={21} color={locked ? '#B5B0BC' : colors.green} /></Pressable></View>; })}{shown.length < filtered.length ? <Pressable onPress={() => setPage((value) => value + 1)} style={styles.loadMore}><Text style={styles.loadMoreText}>再看 30 课</Text></Pressable> : null}</ScrollView>;
}

interface ProgressWord { word_id: string; word: string; current_stage: number; stage_name: string }
function CollectionScreen({ onBack }: { onBack: () => void }) {
  const session = useSession(); const [words, setWords] = useState<Array<ProgressWord & { subject: string }>>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!session.childId) { setLoading(false); return; } void Promise.all(['识字', '英语'].map((subject) => api<{ words: ProgressWord[] }>(`/progress/${encodeURIComponent(subject)}?child_id=${encodeURIComponent(session.childId ?? '')}&page_size=100`).then((result) => result.words.map((item) => ({ ...item, subject }))))).then((parts) => setWords(parts.flat())).catch(() => setWords([])).finally(() => setLoading(false)); }, [session.childId]);
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title="朋友收集册" onBack={onBack} /><View style={styles.collectionHero}><Icon name="sprout" size={42} color={colors.green} /><Text style={styles.collectionTitle}>已经遇见 {words.length} 位朋友</Text><Text style={styles.pageSubtitle}>已相识 → 好朋友 → 好伙伴，只升级不降级</Text></View>{loading ? <Loading /> : null}{!loading && !session.childId ? <Empty text="登录并选择孩子后查看收集册" /> : null}{!loading && session.childId && !words.length ? <Empty text="还没有朋友，先去听一节课吧" /> : null}<View style={styles.collectionGrid}>{words.map((item) => <View key={`${item.subject}-${item.word_id}`} style={[styles.friendCard, item.current_stage >= 3 && styles.friendMaster]}><Text numberOfLines={1} style={styles.friendWord}>{item.word || item.word_id}</Text><Text style={styles.friendStage}>{item.stage_name}</Text><Text style={styles.friendSubject}>{item.subject}</Text></View>)}</View></ScrollView>;
}

interface QuizQuestion { question_id: string; type: string; stem?: string; word?: string; options: Array<{ option_id: string; text: string }> }
interface Quiz { test_id: string; word_id: string; questions: QuizQuestion[] }
interface QuizResult { test_passed: boolean; score: number; feedback: string; results: Array<{ question_id: string; is_correct: boolean; explanation?: string }> }
function ChallengeScreen({ subject, initialLesson, onBack }: { subject: '识字' | '英语'; initialLesson?: LessonEntry; onBack: () => void }) {
  const session = useSession(); const [lesson, setLesson] = useState<LessonEntry | null>(initialLesson ?? null); const [quiz, setQuiz] = useState<Quiz | null>(null); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Array<{ question_id: string; selected_option: string }>>([]); const [result, setResult] = useState<QuizResult | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { if (!lesson) void content.lessons(subject).then((items) => setLesson(items[0] ?? null)); }, [lesson, subject]);
  const start = async () => { if (!session.childId || !lesson) { Alert.alert('请先登录并选择孩子档案'); return; } setLoading(true); setResult(null); setAnswers([]); setIndex(0); try { setQuiz(await api<Quiz>(`/test/quiz/${encodeURIComponent(lesson.id)}?child_id=${encodeURIComponent(session.childId)}&subject=${encodeURIComponent(subject)}&word_text=${encodeURIComponent(lesson.text)}`)); } catch (e) { Alert.alert('取题失败', e instanceof Error ? e.message : '请稍后重试'); } finally { setLoading(false); } };
  const choose = async (option: string) => { if (!quiz || !lesson || !session.childId) return; const question = quiz.questions[index]; if (!question) return; const nextAnswers = [...answers, { question_id: question.question_id, selected_option: option }]; setAnswers(nextAnswers); if (index < quiz.questions.length - 1) { setIndex((value) => value + 1); return; } setLoading(true); try { setResult(await api<QuizResult>(`/test/quiz/${encodeURIComponent(lesson.id)}`, { method: 'POST', body: JSON.stringify({ child_id: session.childId, test_id: quiz.test_id, answers: nextAnswers }) })); setQuiz(null); } catch (e) { Alert.alert('提交失败', e instanceof Error ? e.message : '请重新开始'); setQuiz(null); } finally { setLoading(false); } };
  const question = quiz?.questions[index];
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title="友情大考验" onBack={onBack} /><View style={styles.challengeHero}><Icon name="star" size={45} color="#F2B51D" /><Text style={styles.challengeTitle}>{lesson ? `和“${lesson.text}”成为好朋友` : '准备挑战'}</Text><Text style={styles.pageSubtitle}>答错没有惩罚，可以一直重试</Text></View>{loading ? <Loading label="挑战准备中…" /> : null}{!loading && !quiz && !result ? <View style={styles.challengeStart}><PrimaryButton title="开始挑战" onPress={() => void start()} /></View> : null}{question ? <View style={styles.questionCard}><Text style={styles.questionCount}>第 {index + 1} / {quiz?.questions.length} 题</Text>{question.word ? <Text style={styles.questionWord}>{question.word}</Text> : null}<Text style={styles.questionStem}>{question.stem ?? '请选择正确答案'}</Text>{question.options.map((option) => <Pressable key={option.option_id} onPress={() => void choose(option.option_id)} style={styles.option}><Text style={styles.optionId}>{option.option_id}</Text><Text style={styles.optionText}>{option.text}</Text></Pressable>)}</View> : null}{result ? <View style={styles.resultCard}><Icon name={result.test_passed ? 'check' : 'refresh'} size={55} color={result.test_passed ? colors.green : colors.orange} /><Text style={styles.resultScore}>{result.score} 分</Text><Text style={styles.resultFeedback}>{result.feedback}</Text><PrimaryButton title={result.test_passed ? '完成' : '再试一次'} onPress={result.test_passed ? onBack : () => void start()} /></View> : null}</ScrollView>;
}

function SettingsScreen({ onBack }: { onBack: () => void }) {
  const player = usePlayer(); const [dark, setDark] = useState(false); const [sleep, setSleep] = useState(false);
  return <ScrollView style={styles.cream} contentContainerStyle={styles.pageContent}><Header title="账号设置" onBack={onBack} /><SectionHeader title="外观与播放" /><SettingRow icon="moon" title="夜间模式" note="当前页面预览；全局主题仍在逐页接入"><Switch value={dark} onValueChange={setDark} trackColor={{ true: colors.orange }} /></SettingRow><SettingRow icon="timer" title="睡眠定时" note={sleep ? '30 分钟后暂停' : '未开启'}><Switch value={sleep} onValueChange={(value) => { setSleep(value); player.setSleepTimer(value ? 30 : null); }} trackColor={{ true: colors.orange }} /></SettingRow><SettingRow icon="vol" title="默认倍速" note="播放器内五档循环"><Pressable onPress={player.cycleRate}><Text style={styles.settingValue}>{player.playbackRate.toFixed(1)}x</Text></Pressable></SettingRow><SettingRow icon="refresh" title="播放模式" note="点按切换"><Pressable onPress={player.cycleMode}><Text style={styles.settingValue}>{MODE_TEXT[player.playMode]}</Text></Pressable></SettingRow><SectionHeader title="关于" /><Card><Text style={styles.rowTitle}>酷酷儿童故事 App</Text><Text style={styles.tip}>Android / iOS 独立发布，不导入微信小程序运行时、身份或支付配置。</Text></Card></ScrollView>;
}
const MODE_TEXT = { order: '顺序', 'repeat-all': '列表循环', 'repeat-one': '单曲循环' } as const;
function SettingRow({ icon, title, note, children }: React.PropsWithChildren<{ icon: 'moon' | 'timer' | 'vol' | 'refresh'; title: string; note: string }>) { return <View style={styles.settingRow}><View style={styles.settingIcon}><Icon name={icon} size={23} color={colors.orange} /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowNote}>{note}</Text></View>{children}</View>; }

function MembershipScreen({ onBack }: { onBack: () => void }) {
  const session = useSession(); const active = session.profile?.can_access_all === true; const member = session.profile?.membership.status === 'active';
  return <ScrollView style={styles.goldPage} contentContainerStyle={styles.pageContent}><Header title="鎏金故事书匣" onBack={onBack} /><View style={styles.memberHero}><Icon name="crown" size={70} color="#FFE49A" /><Text style={styles.memberTitle}>鎏金故事书匣</Text><Text style={styles.memberSub}>全馆故事与儿歌 · 成长进阶内容 · 无广告纯净</Text><StatusPill tone={active ? 'green' : 'gold'}>{member ? '会员权益已生效' : active ? '活动体验期内' : '当前为非权益状态'}</StatusPill></View><View style={styles.benefit}><Icon name="book" size={27} color="#FFE49A" /><Text style={styles.benefitText}>名著全集与全库故事连续播放</Text></View><View style={styles.benefit}><Icon name="moon" size={27} color="#FFE49A" /><Text style={styles.benefitText}>睡前故事、锁屏与后台播放</Text></View><View style={styles.benefit}><Icon name="star" size={27} color="#FFE49A" /><Text style={styles.benefitText}>成长进阶内容与友情挑战</Text></View><Card><Text style={styles.rowTitle}>App 购买通道尚未开放</Text><Text style={styles.tip}>正式售卖前必须分别接入 Apple App Store 与 Google Play 内购，并由服务端验证票据、退款和权益同步。不会复用微信小程序订单或微信支付。</Text></Card></ScrollView>;
}

function ContentRow({ title, note, image, onPress }: { title: string; note: string; image?: string; onPress: () => void }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.contentRow, pressed && { opacity: .72 }]}><Cover uri={image} /><View style={{ flex: 1 }}><Text numberOfLines={2} style={styles.rowTitle}>{title}</Text><Text numberOfLines={1} style={styles.rowNote}>{note}</Text></View><View style={styles.rowPlay}><Icon name="play" size={18} color="#fff" /></View></Pressable>; }

const styles = StyleSheet.create({
  cream: { flex: 1, backgroundColor: '#FFF9F0' }, goldPage: { flex: 1, backgroundColor: '#211E17' }, pageContent: { paddingBottom: 36 }, header: { minHeight: 62, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerButton: { width: 50, height: 50, alignItems: 'center', justifyContent: 'center' }, headerTitle: { color: colors.ink, fontSize: 21, fontWeight: '900' }, headerAction: { color: colors.orange, fontWeight: '800' }, pageSubtitle: { color: colors.muted, marginHorizontal: 20, marginBottom: 14, textAlign: 'center' },
  segment: { marginHorizontal: 16, padding: 5, borderRadius: 22, backgroundColor: '#fff', flexDirection: 'row', borderWidth: 1, borderColor: colors.line }, segmentButton: { flex: 1, minHeight: 44, borderRadius: 18, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center' }, segmentActive: { backgroundColor: colors.orange }, segmentText: { color: colors.orange, fontWeight: '900' }, segmentTextActive: { color: '#fff' },
  contentRow: { minHeight: 92, marginHorizontal: 16, marginBottom: 10, padding: 10, borderRadius: 22, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 12 }, rowTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, rowNote: { color: colors.muted, fontSize: 12, marginTop: 6 }, rowPlay: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  searchBox: { minHeight: 54, marginHorizontal: 16, paddingHorizontal: 16, borderRadius: 27, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 10 }, searchInput: { flex: 1, color: colors.ink, fontSize: 16, outlineStyle: 'none' } as never, chips: { paddingHorizontal: 18, flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, chip: { paddingHorizontal: 18, paddingVertical: 11, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line }, chipText: { color: colors.ink, fontWeight: '700' }, tip: { color: colors.muted, lineHeight: 22, marginBottom: 8 },
  manageRow: { minHeight: 94, marginHorizontal: 16, marginBottom: 10, padding: 10, borderRadius: 22, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center' }, manageMain: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 }, removeButton: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12 }, removeText: { color: '#D84A32', fontWeight: '900' },
  addRow: { marginHorizontal: 16, marginBottom: 18, flexDirection: 'row', gap: 10 }, nameInput: { flex: 1, minHeight: 50, paddingHorizontal: 16, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line }, addButton: { minWidth: 80, borderRadius: 18, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' }, addText: { color: '#fff', fontWeight: '900' }, childRow: { minHeight: 78, marginHorizontal: 16, marginBottom: 10, padding: 12, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 12 }, childAvatar: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#EEE8FF', alignItems: 'center', justifyContent: 'center' },
  filterRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, marginBottom: 16 }, filter: { minHeight: 42, paddingHorizontal: 18, borderRadius: 18, backgroundColor: '#fff', borderWidth: 1, borderColor: '#CDE7C9', alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: colors.green }, filterText: { color: colors.green, fontWeight: '800' }, filterTextActive: { color: '#fff' }, lessonRow: { minHeight: 86, marginHorizontal: 16, marginBottom: 10, padding: 10, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: '#D9EAD6' }, lessonMain: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 }, lessonWord: { width: 64, height: 64, borderRadius: 17, backgroundColor: '#E8F6E5', alignItems: 'center', justifyContent: 'center' }, lessonEnglish: { width: 92, backgroundColor: '#E8F2FF' }, lessonWordText: { color: '#347E31', fontSize: 27, fontWeight: '900' }, lessonEnglishText: { color: '#3174BE', fontSize: 16 }, loadMore: { minHeight: 48, marginHorizontal: 60, borderRadius: 24, backgroundColor: '#E7F6E4', alignItems: 'center', justifyContent: 'center' }, loadMoreText: { color: colors.green, fontWeight: '900' },
  collectionHero: { marginHorizontal: 16, padding: 20, borderRadius: 24, backgroundColor: '#fff', borderWidth: 1, borderColor: '#D9EAD6', alignItems: 'center' }, collectionTitle: { color: colors.ink, fontSize: 21, fontWeight: '900', marginTop: 9 }, collectionGrid: { paddingHorizontal: 16, flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 16 }, friendCard: { width: '31.3%', minHeight: 112, borderRadius: 20, backgroundColor: '#E8F6E5', borderWidth: 1, borderColor: '#CDE7C9', alignItems: 'center', justifyContent: 'center', padding: 8 }, friendMaster: { backgroundColor: '#FFF3CE', borderColor: '#F1CC6D' }, friendWord: { color: colors.ink, fontSize: 27, fontWeight: '900' }, friendStage: { color: colors.green, fontSize: 11, fontWeight: '800', marginTop: 6 }, friendSubject: { color: colors.muted, fontSize: 10, marginTop: 3 },
  challengeHero: { alignItems: 'center', padding: 18 }, challengeTitle: { color: colors.ink, fontSize: 22, fontWeight: '900', marginTop: 8 }, challengeStart: { marginHorizontal: 44, marginTop: 20 }, questionCard: { margin: 16, padding: 20, borderRadius: 26, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line }, questionCount: { color: colors.orange, fontWeight: '900' }, questionWord: { color: colors.ink, fontSize: 54, textAlign: 'center', fontWeight: '900', marginTop: 14 }, questionStem: { color: colors.ink, fontSize: 19, lineHeight: 27, fontWeight: '800', textAlign: 'center', marginVertical: 18 }, option: { minHeight: 56, borderRadius: 18, backgroundColor: '#FFF5EC', marginBottom: 10, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: colors.line }, optionId: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.orange, color: '#fff', textAlign: 'center', lineHeight: 32, fontWeight: '900' }, optionText: { color: colors.ink, flex: 1, fontWeight: '700' }, resultCard: { margin: 16, padding: 24, borderRadius: 26, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, alignItems: 'center', gap: 12 }, resultScore: { color: colors.ink, fontSize: 42, fontWeight: '900' }, resultFeedback: { color: colors.muted, fontSize: 17, marginBottom: 8 },
  settingRow: { minHeight: 76, marginHorizontal: 16, marginBottom: 10, padding: 14, borderRadius: 20, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 12 }, settingIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#FFF0E5', alignItems: 'center', justifyContent: 'center' }, settingValue: { color: colors.orange, fontWeight: '900' },
  memberHero: { margin: 16, padding: 24, borderRadius: 28, borderWidth: 1, borderColor: '#8A6A2C', backgroundColor: '#342F23', alignItems: 'center' }, memberTitle: { color: '#FFE49A', fontSize: 31, fontWeight: '900', marginTop: 12 }, memberSub: { color: '#BEB49C', textAlign: 'center', lineHeight: 21, marginVertical: 13 }, benefit: { minHeight: 76, marginHorizontal: 16, marginBottom: 10, paddingHorizontal: 18, borderRadius: 20, borderWidth: 1, borderColor: '#6B5730', backgroundColor: '#302B20', flexDirection: 'row', alignItems: 'center', gap: 14 }, benefitText: { color: '#EFE2BD', fontWeight: '800', flex: 1 },
});
